
import { LanguageOption, SupportedLanguageCode } from './types';

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', name: 'English', nativeName: 'English', ttsLocale: 'en-US', flag: '🇺🇸' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', ttsLocale: 'id-ID', flag: '🇮🇩' },
  { code: 'zh', name: 'Chinese', nativeName: '普通话', ttsLocale: 'zh-CN', flag: '🇨🇳' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', ttsLocale: 'es-ES', flag: '🇪🇸' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', ttsLocale: 'ko-KR', flag: '🇰🇷' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', ttsLocale: 'ja-JP', flag: '🇯🇵' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', ttsLocale: 'nl-NL', flag: '🇳🇱' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', ttsLocale: 'ar-SA', flag: '🇸🇦' },
];

export const I18N: Record<SupportedLanguageCode, Record<string, string>> = {
  en: {
    voice: "Voice", dictate: "Dictate", text: "Text", photo: "Photo",
    mother_lang: "Your Language (Auto-Detect)", translate_to: "Translate To",
    mic_sensitivity: "Mic Sensitivity", playback_volume: "Playback Volume",
    hold_to_speak: "Hold to Speak", listening: "Listening Now", processing: "Processing...",
    scanning: "Scanning Image...", retry: "Retry", translate_photo: "Translate Photo",
    translate: "Translate", type_placeholder: "Type or paste text...",
    history: "History", saved_entries: "Saved Entries", history_empty: "History is empty",
    clear_history: "Clear Entire History", dismiss: "Dismiss", detected: "Detected",
    sign_in: "Sign In", sign_up: "Sign Up", start_now: "Start Now",
    welcome: "Welcome to IVoice", choose_lang: "Choose your language to start",
    step_config: "Step 1: Configuration", ctrl_enter: "Ctrl + Enter to send",
    quiet: "Quiet", standard: "Standard", boost: "Boost",
    muted: "Muted", half: "Half", full: "Full",
    capture_hint: "Take a photo or upload a screenshot",
    empty_hint: "Speak or type to translate",
    auto_detect: "Auto-Detect Active",
    premium_title: "Unlock Global Limits",
    premium_desc: "You've reached your daily free limit. Upgrade to IVoice Premium for unlimited magical translations.",
    premium_button: "Unlock Premium for $11/week",
    restore_purchase: "Restore Purchase",
    daily_limit_hit: "Daily limit reached. Upgrade for more!",
    premium_feature_1: "Unlimited Daily Translations",
    premium_feature_2: "Full Voice Synthesis Quality",
    premium_feature_3: "Ad-Free Magical Experience",
    premium_feature_4: "Offline Translation Mode",
    offline_mode: "Offline Mode",
    offline_active: "Local Engine Active",
    download_packs: "Offline Language Packs",
    download: "Download",
    downloading: "Downloading...",
    downloaded: "Downloaded",
    premium_only: "Premium Feature Only",
    offline_engine_ready: "Offline translation ready for this language"
  },
  id: {
    voice: "Suara", dictate: "Dikte", text: "Teks", photo: "Foto",
    mother_lang: "Bahasa Anda (Deteksi Otomatis)", translate_to: "Terjemahkan Ke",
    mic_sensitivity: "Sensitivitas Mik", playback_volume: "Volume Putar",
    hold_to_speak: "Tahan untuk Bicara", listening: "Mendengarkan...", processing: "Memproses...",
    scanning: "Memindai Gambar...", retry: "Ulangi", translate_photo: "Terjemahkan Foto",
    translate: "Terjemahkan", type_placeholder: "Ketik atau tempel teks...",
    history: "Riwayat", saved_entries: "Entri Tersimpan", history_empty: "Riwayat kosong",
    clear_history: "Hapus Semua Riwayat", dismiss: "Tutup", detected: "Terdeteksi",
    sign_in: "Masuk", sign_up: "Daftar", start_now: "Mulai Sekarang",
    welcome: "Selamat datang di IVoice", choose_lang: "Pilih bahasa Anda untuk memulai",
    step_config: "Langkah 1: Konfigurasi", ctrl_enter: "Ctrl + Enter untuk kirim",
    quiet: "Sepi", standard: "Standar", boost: "Tinggi",
    muted: "Bisu", half: "Setengah", full: "Penuh",
    capture_hint: "Ambil foto atau unggah tangkapan layar",
    empty_hint: "Bicara atau ketik untuk menerjemahkan",
    auto_detect: "Deteksi Otomatis Aktif",
    premium_title: "Buka Batas Global",
    premium_desc: "Anda telah mencapai batas harian gratis. Tingkatkan ke IVoice Premium untuk terjemahan ajaib tanpa batas.",
    premium_button: "Buka Premium seharga $11/minggu",
    restore_purchase: "Pulihkan Pembelian",
    daily_limit_hit: "Batas harian tercapai. Tingkatkan sekarang!",
    premium_feature_1: "Terjemahan Harian Tanpa Batas",
    premium_feature_2: "Kualitas Sintesis Suara Penuh",
    premium_feature_3: "Pengalaman Ajaib Tanpa Iklan",
    premium_feature_4: "Mode Terjemahan Offline",
    offline_mode: "Mode Offline",
    offline_active: "Mesin Lokal Aktif",
    download_packs: "Paket Bahasa Offline",
    download: "Unduh",
    downloading: "Mengunduh...",
    downloaded: "Terunduh",
    premium_only: "Fitur Khusus Premium",
    offline_engine_ready: "Terjemahan offline siap untuk bahasa ini"
  },
  zh: {
    voice: "语音", dictate: "听写", text: "文本", photo: "照片",
    mother_lang: "您的语言（自动检测）", translate_to: "翻译为",
    mic_sensitivity: "麦克风灵敏度", playback_volume: "回放音量",
    hold_to_speak: "按住说话", listening: "正在聆听...", processing: "正在处理...",
    scanning: "正在扫描图像...", retry: "重试", translate_photo: "翻译照片",
    translate: "翻译", type_placeholder: "输入或粘贴文本...",
    history: "历史记录", saved_entries: "已保存的条目", history_empty: "历史记录为空",
    clear_history: "清除所有历史记录", dismiss: "忽略", detected: "检测到",
    sign_in: "登录", sign_up: "注册", start_now: "立即开始",
    welcome: "欢迎来到 IVoice", choose_lang: "选择您的语言以开始",
    step_config: "步骤 1：配置", ctrl_enter: "Ctrl + Enter 发送",
    quiet: "安静", standard: "标准", boost: "增强",
    muted: "静音", half: "一半", full: "全量",
    capture_hint: "拍照或上传屏幕截图",
    empty_hint: "说话或打字进行翻译",
    auto_detect: "自动检测已启用",
    premium_title: "解锁全球限制",
    premium_desc: "您已达到每日免费限制。升级至 IVoice Premium 以获得无限神奇翻译。",
    premium_button: "以每周 $11 解锁高级版",
    restore_purchase: "恢复购买",
    daily_limit_hit: "已达到每日限制。请升级以获取更多！",
    premium_feature_1: "无限每日翻译",
    premium_feature_2: "全语音合成质量",
    premium_feature_3: "无广告的神奇体验",
    premium_feature_4: "离线翻译模式",
    offline_mode: "离线模式",
    offline_active: "本地引擎已激活",
    download_packs: "离线语言包",
    download: "下载",
    downloading: "正在下载...",
    downloaded: "已下载",
    premium_only: "仅限高级功能",
    offline_engine_ready: "该语言的离线翻译已就绪"
  },
  es: {
    voice: "Voz", dictate: "Dictado", text: "Texto", photo: "Foto",
    mother_lang: "Tu Idioma (Autodetección)", translate_to: "Traducir A",
    mic_sensitivity: "Sensibilidad Mic", playback_volume: "Volumen Reproducción",
    hold_to_speak: "Mantén para Hablar", listening: "Escuchando...", processing: "Procesando...",
    scanning: "Escaneando Imagen...", retry: "Reintentar", translate_photo: "Traducir Foto",
    translate: "Traducir", type_placeholder: "Escribe o pega texto...",
    history: "Historial", saved_entries: "Entradas Guardadas", history_empty: "El historial está vacío",
    clear_history: "Borrar Todo el Historial", dismiss: "Cerrar", detected: "Detectado",
    sign_in: "Iniciar Sesión", sign_up: "Registrarse", start_now: "Empezar Ahora",
    welcome: "Bienvenido a IVoice", choose_lang: "Elige tu idioma para empezar",
    step_config: "Paso 1: Configuración", ctrl_enter: "Ctrl + Enter para enviar",
    quiet: "Silencio", standard: "Estándar", boost: "Aumento",
    muted: "Mudo", half: "Medio", full: "Total",
    capture_hint: "Toma una foto o sube una captura",
    empty_hint: "Habla o escribe para traducir",
    auto_detect: "Detección Automática",
    premium_title: "Desbloquea Límites Globales",
    premium_desc: "Has alcanzado tu límite diario gratuito. Actualiza a IVoice Premium para traducciones mágicas ilimitadas.",
    premium_button: "Desbloquear Premium por $11/semana",
    restore_purchase: "Restaurar Compra",
    daily_limit_hit: "Límite diario alcanzado. ¡Actualiza para más!",
    premium_feature_1: "Traducciones Diarias Ilimitadas",
    premium_feature_2: "Calidad Total de Síntesis de Voz",
    premium_feature_3: "Experiencia Mágica sin Anuncios",
    premium_feature_4: "Modo de Traducción Offline",
    offline_mode: "Modo Offline",
    offline_active: "Motor Local Activo",
    download_packs: "Paquetes de Idioma Offline",
    download: "Descargar",
    downloading: "Descargando...",
    downloaded: "Descargado",
    premium_only: "Solo para Usuarios Premium",
    offline_engine_ready: "Traducción offline lista para este idioma"
  },
  ko: {
    voice: "음성", dictate: "받아쓰기", text: "텍스트", photo: "사진",
    mother_lang: "나의 언어 (자동 감지)", translate_to: "번역할 언어",
    mic_sensitivity: "마이크 감도", playback_volume: "재생 볼륨",
    hold_to_speak: "말하려면 누르세요", listening: "듣는 중...", processing: "처리 중...",
    scanning: "이미지 스캔 중...", retry: "다시 시도", translate_photo: "사진 번역",
    translate: "번역", type_placeholder: "텍스트를 입력하거나 붙여넣으세요...",
    history: "기록", saved_entries: "저장된 항목", history_empty: "기록이 비어 있습니다",
    clear_history: "전체 기록 삭제", dismiss: "닫기", detected: "감지됨",
    sign_in: "로그인", sign_up: "회원가입", start_now: "지금 시작",
    welcome: "IVoice에 오신 것을 환영합니다", choose_lang: "시작하려면 언어를 선택하세요",
    step_config: "1단계: 설정", ctrl_enter: "Ctrl + Enter로 전송",
    quiet: "조용함", standard: "표준", boost: "강화",
    muted: "음소거", half: "절반", full: "전체",
    capture_hint: "사진을 찍거나 스크린샷을 업로드하세요",
    empty_hint: "번역하려면 말하거나 입력하세요",
    auto_detect: "자동 감지 활성화",
    premium_title: "글로벌 한도 해제",
    premium_desc: "오늘의 무료 한도에 도달했습니다. 무제한 마법 번역을 위해 IVoice Premium으로 업그레이드하세요.",
    premium_button: "주당 $11로 프리미엄 해제",
    restore_purchase: "구매 복원",
    daily_limit_hit: "일일 한도에 도달했습니다. 더 많은 기능을 위해 업그레이드하세요!",
    premium_feature_1: "무제한 일일 번역",
    premium_feature_2: "완벽한 음성 합성 품질",
    premium_feature_3: "광고 없는 마법 같은 경험",
    premium_feature_4: "오프라인 번역 모드",
    offline_mode: "오프라인 모드",
    offline_active: "로컬 엔진 활성화",
    download_packs: "오프라인 언어 팩",
    download: "다운로드",
    downloading: "다운로드 중...",
    downloaded: "다운로드됨",
    premium_only: "프리미엄 전용 기능",
    offline_engine_ready: "이 언어의 오프라인 번역이 준비되었습니다"
  },
  ja: {
    voice: "音声", dictate: "ディクテーション", text: "テキスト", photo: "写真",
    mother_lang: "あなたの言語（自動検出）", translate_to: "翻訳先",
    mic_sensitivity: "マイク感度", playback_volume: "再生音量",
    hold_to_speak: "長押しして話す", listening: "聞き取り中...", processing: "処理中...",
    scanning: "画像をスキャン中...", retry: "再試行", translate_photo: "写真を翻訳",
    translate: "翻译", type_placeholder: "テキストを入力または貼り付け...",
    history: "履歴", saved_entries: "保存済み", history_empty: "履歴はありません",
    clear_history: "履歴をすべて削除", dismiss: "閉じる", detected: "検出済み",
    sign_in: "サインイン", sign_up: "サインアップ", start_now: "今すぐ開始",
    welcome: "IVoiceへようこそ", choose_lang: "開始する言語を選択してください",
    step_config: "ステップ 1：設定", ctrl_enter: "Ctrl + Enter で送信",
    quiet: "静か", standard: "標準", boost: "ブースト",
    muted: "ミュート", half: "半分", full: "最大",
    capture_hint: "写真を撮るかスクリーンショットをアップロード",
    empty_hint: "話すか入力して翻訳",
    auto_detect: "自動検出中",
    premium_title: "グローバル制限を解除",
    premium_desc: "1日の無料制限に達しました。無制限の魔法のような翻訳を利用するには、IVoice Premiumにアップグレードしてください。",
    premium_button: "週11ドルでプレミアムを解除",
    restore_purchase: "購入を復元",
    daily_limit_hit: "1日の制限に達しました。アップグレードしてさらに使いましょう！",
    premium_feature_1: "無制限の翻訳",
    premium_feature_2: "最高品質の音声合成",
    premium_feature_3: "広告なしの魔法体験",
    premium_feature_4: "オフライン翻訳モード",
    offline_mode: "オフラインモード",
    offline_active: "ローカルエンジンが作動中",
    download_packs: "オフライン言語パック",
    download: "ダウンロード",
    downloading: "ダウンロード中...",
    downloaded: "ダウンロード済み",
    premium_only: "プレミアム限定機能",
    offline_engine_ready: "この言語のオフライン翻訳が利用可能です"
  },
  nl: {
    voice: "Stem", dictate: "Dicteren", text: "Tekst", photo: "Foto",
    mother_lang: "Uw Taal (Auto-Detectie)", translate_to: "Vertalen Naar",
    mic_sensitivity: "Microfoongevoeligheid", playback_volume: "Afspeelvolume",
    hold_to_speak: "Vasthouden om te Spreken", listening: "Luisteren...", processing: "Verwerken...",
    scanning: "Afbeelding Scannen...", retry: "Opnieuw", translate_photo: "Foto Vertalen",
    translate: "Vertalen", type_placeholder: "Typ of plak tekst...",
    history: "Geschiedenis", saved_entries: "Opgeslagen Items", history_empty: "Geschiedenis is leeg",
    clear_history: "Wis Gehele Geschiedenis", dismiss: "Sluiten", detected: "Gedetecteerd",
    sign_in: "Inloggen", sign_up: "Aanmelden", start_now: "Nu Starten",
    welcome: "Welkom bij IVoice", choose_lang: "Kies uw taal om te beginnen",
    step_config: "Stap 1: Configuratie", ctrl_enter: "Ctrl + Enter om te verzenden",
    quiet: "Stil", standard: "Standaard", boost: "Versterkt",
    muted: "Gedempt", half: "Helft", full: "Volledig",
    capture_hint: "Maak een foto of upload een screenshot",
    empty_hint: "Spreek of typ om te vertalen",
    auto_detect: "Automatische Detectie",
    premium_title: "Ontgrendel Wereldwijde Limieten",
    premium_desc: "U heeft uw dagelijkse gratis limiet bereikt. Upgrade naar IVoice Premium voor onbeperkte magische vertalingen.",
    premium_button: "Ontgrendel Premium voor $11/week",
    restore_purchase: "Aankoop Herstellen",
    daily_limit_hit: "Daglimiet bereikt. Upgrade voor meer!",
    premium_feature_1: "Onbeperkte Dagelijkse Vertalingen",
    premium_feature_2: "Volledige Stemkwaliteit",
    premium_feature_3: "Advertentievrije Magische Ervaring",
    premium_feature_4: "Offline Vertaalmodus",
    offline_mode: "Offline Modus",
    offline_active: "Lokale Engine Actief",
    download_packs: "Offline Taalpakketten",
    download: "Download",
    downloading: "Downloaden...",
    downloaded: "Gedownload",
    premium_only: "Alleen voor Premium Gebruikers",
    offline_engine_ready: "Offline vertaling klaar voor deze taal"
  },
  ar: {
    voice: "صوت", dictate: "إملاء", text: "نص", photo: "صورة",
    mother_lang: "لغتك (كشف تلقائي)", translate_to: "ترجم إلى",
    mic_sensitivity: "حساسية الميكروفون", playback_volume: "مستوى صوت التشغيل",
    hold_to_speak: "اضغط للتحدث", listening: "جاري الاستماع...", processing: "جاري المعالجة...",
    scanning: "جاري مسح الصورة...", retry: "إعادة المحاولة", translate_photo: "ترجمة الصورة",
    translate: "ترجمة", type_placeholder: "اكتب أو الصق النص هنا...",
    history: "السجل", saved_entries: "المدخلات المحفوظة", history_empty: "السجل فارغ",
    clear_history: "مسح السجل بالكامل", dismiss: "إغلاق", detected: "تم الكشف",
    sign_in: "تسجيل الدخول", sign_up: "إنشاء حساب", start_now: "ابدأ الآن",
    welcome: "مرحباً بك في IVoice", choose_lang: "اختر لغتك للبدء",
    step_config: "الخطوة 1: الإعداد", ctrl_enter: "Ctrl + Enter للإرسال",
    quiet: "هادئ", standard: "قياسي", boost: "تعزيز",
    muted: "كتم", half: "نصف", full: "كامل",
    capture_hint: "التقط صورة أو ارفع لقطة شاشة",
    empty_hint: "تحدث أو اكتب للترجمة",
    auto_detect: "الكشف التلقائي نشط",
    premium_title: "فتح الحدود العالمية",
    premium_desc: "لقد وصلت إلى الحد اليومي المجاني. قم بالترقية إلى IVoice Premium للحصول على ترجمات سحرية غير محدودة.",
    premium_button: "فتح الإصدار المميز مقابل 11 دولاراً في الأسبوع",
    restore_purchase: "استعادة المشتريات",
    daily_limit_hit: "تم الوصول إلى الحد اليومي. قم بالترقية للمزيد!",
    premium_feature_1: "ترجمات يومية غير محدودة",
    premium_feature_2: "جودة تركيب صوت كاملة",
    premium_feature_3: "تجربة سحرية خالية من الإعلانات",
    premium_feature_4: "وضع الترجمة دون اتصال",
    offline_mode: "وضع عدم الاتصال",
    offline_active: "المحرك المحلي نشط",
    download_packs: "حزم اللغات دون اتصال",
    download: "تحميل",
    downloading: "جاري التحميل...",
    downloaded: "تم التحميل",
    premium_only: "ميزة حصرية للمشتركين",
    offline_engine_ready: "الترجمة دون اتصال جاهزة لهذه اللغة"
  }
};

export const SYSTEM_INSTRUCTION = `
You are a high-performance, real-time universal translation engine. Your primary strength is AUTOMATIC LANGUAGE DETECTION.

CONTEXT:
The user has a "Preferred Language" (Mother Language) and a "Target Language".

SUPPORTED LANGUAGES (8):
English, Indonesian, Chinese (Mandarin), Spanish, Korean, Japanese, Dutch, and Arabic.

OPERATIONAL RULES:
1. Universal Auto-Detection:
   - Always analyze the input audio/text to detect which of the 8 supported languages is being spoken.
   - You MUST be able to switch translation direction instantly based on the speaker.

2. Smart 2-Way Translation Logic:
   - IF the speaker is using the user's "Mother Language" -> Translate it into the "Target Language".
   - IF the speaker is using ANY OTHER LANGUAGE (including the Target Language) -> Translate it into the user's "Mother Language".
   - This ensures the user always understands the other person, and the other person always understands the user, without manually switching "Source" languages.

3. Output Format: Provide the response in a structured JSON format only:
   {
     "original_text": "The transcribed text in the source language",
     "detected_language": "The ISO code of the source language (e.g., 'id', 'es', 'ja')",
     "translated_text": "The final translation",
     "phonetic": "A phonetic transcription to help with pronunciation (required for Chinese, Korean, Japanese, Arabic)"
   }

4. Tone & Nuance: Maintain the original speaker's tone (formal/informal/emotional).

5. No Chatter: Only provide the JSON object. No explanations or greetings.
`;
